# Generated by Django 4.1 on 2023-02-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
